server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/jvmexplorer
spring.datasource.username=jvmexplorer
spring.datasource.password=jvmexplorer
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
